### PR TITLE
Fix all the tests

### PR DESCRIPTION
**Pull request by zauguin**
Recently some of our tests failed because used fonts added/modified characters.
I believe that for all failures fixed here we are not to blame but this PR is just supposed to ensure that I don't accidentally hide "real" bugs...

### CODE REVIEW

**Comment by u-fischer** [comment]
The arab failures and invisible char looks like side effects from the newest amiri version. But the math-stix2 failure is odd and the numbers are quite high and there are suspicious font spec messages in the log. I wonder if unicode-math broke something here.

**Comment by zauguin** [comment]
@u-fischer It looks like the real change in math-stix2 is the disappearing hbox

    \hbox(0.0+0.0)x207.0021, glue set 103.50105fil, direction TLT

which didn't have any content (beside two \hfills) anyway.
Now I don't really see where this box comes from in the first place, the code there is just

```
\START \showoutput
```

So for me it is more likely that unicode-math fixed something, rather than broke.

**Comment by u-fischer** [comment]
@zauguin the difference is that unicode-math is now loading amsmath by default - and this has some dramatic effects on the output. When I load amsmath in texlive 2018 I get similar values. So it is not our fault and remaking the test is okay.

**Comment by zauguin** [comment]
@u-fischer Oh, thank you. I wasn't aware of that change. That probably also explains the other test failure on Travis: The sqrt test without amsmath no longer makes sense if amsmath is loaded anyway.

I'm just confused why Travis did run these tests in the first place. The dev branch detection seems to be broken. But that's another issue...

**Pull request merged**
