### PR TITLE
Merge of #81 and #82

### PR DESCRIPTION
**Pull request by zauguin**

### CODE REVIEW

**Comment by u-fischer** [comment]
@jbezos probably some unicode files are not found. e.g. the lua looks for OpentypeMirroring.txt. I can look at it in a few hours and try to build a test branch.

**Comment by u-fischer** [comment]
@zauguin  @jbezos  I merged the bidi pull request and also the code in the mirror branch in a new branch "bidi-dev". In view of the discussion in unicode-data I renamed the mirroring.txt-file to BidiMirroring-510.txt. 

I'm not sure if the combination of mirror + bidi does the right thing as I have no idea what the right thing is here - but I guess this can be sorted out later. 

Currently there are three failures in the tests: the arab1, arab2 and arab3 and invisible-chars have additional direction nodes. That is probably ok. 

@jbezos if you want to test:

* we have setup branches with "dev" so that they install the luaotfload files in tex/latex-dev. This means that you should try them out with `lualatex-dev`. The version number in the log should be 3.0004.

*  the new versions need an up-to-date unicode-data

* the new versions needs also a file not yet in unicode-data, BidiMirroring-510.txt, which is (temporarly) in the src and the texmf folder of luaotfload.

**Comment by jbezos** [comment]
It's now working and in my first quick tests all chars are in place (but parenthesis are reversed).

**Comment by u-fischer** [comment]
@jbezos it was perhaps an error that I pulled in the mirror code too - perhaps the parentheses are now switched twice @zauguin will know.

**Comment by zauguin** [comment]
@u-fischer @jbezos The additional direction nodes should not make a difference, the bidi code just ensures that they are actually balanced. I *think* that's what LuaTeX does internally anyway. The reversed parentheses are to be expected because the bidi code is older than the mirror code, so it mirrors them too. We just have to remove the mirror stuff from bidi. Also I think we agreed on `BidiMirroring-5-1-0.txt`, but we can sort that out when it is committed in unicode-data.

**Comment by jbezos** [comment]
The odd thing is it only happens with Arial. I've just tested it with other fonts and everything is fine. Maybe my copy of Arial is buggy. The important thing is I can do tests.

**Comment by jbezos** [comment]
I think there are some misplaced symbols in the following file:

```
\documentclass{article}

\usepackage{fontspec}

\setmainfont[Script=Arabic,RawFeature=+bidi]{FreeSerif}

\begin{document}

\pardir TRT \textdir TRT \bodydir TRT \pagedir TRT

بى £ تى az £ ثى bz £ cz سى £ dz شى 19£ صى \$29 ضى ez 39£ طى 49£ fz ظى

\end{document}
```
The expected result is:

et-bidi

but I'm getting:

et-bidi-2

[test-bidi-et.zip](https://github.com/latex3/luaotfload/files/3538546/test-bidi-et.zip)

**Comment by zauguin** [comment]
@jbezos Thanks, both the mirroring and the other problem should be fixed in bidi-dev. Could you test again?

**Comment by u-fischer** [comment]
This has been merged into bidi-dev.

**Pull request closed without merging**
