### PR TITLE
[WIP] Bidi

### PR DESCRIPTION
**Pull request by zauguin**
Support for the Unicode bidirectional algorithm.

```
\font\myfont "Arial:+bidi" -- Arial supports all these scripts 
\myfont
typesetting στοιχειοθεσία ﺺﻓ ﺎﻠﺣﺭﻮﻓ 
\bye
```
image
Mostly intended for use with #81, look there for a combined example.

### CODE REVIEW

**Comment by khaledhosny** [comment]
Is this implementation from scratch and does it pass the UBA tests? FWIW there is a Lua implementation in https://github.com/ufyTeX/luabidi/.

**Comment by u-fischer** [comment]
I get a merge conflict with the previous PR, in main and init. The one loads/use multiscript the other bidi. How should they be combined?

**Comment by zauguin** [comment]
@u-fischer See my `multibidi` branch for a merged version, I can also update this PR later.

@khaledhosny This is a form scratch implementation, mostly because I wanted to work directly with nodes, so it is rather TeX specific. (Also this was mostly an excuse to get familiar with the Bidi algorithm)

About the UBA tests: The current version has been tested with `BidiCharacterTest.txt`. All applicable test succeed, which means all test failures are related to the following implementation details:

- "Sements/Paragraph separators always have paragraph direction" (half of L1)  is not implemented because I first wanted to figure out if these characters can even appear in a normal TeX document. This does not have any side effects.
- LuaTeX dir nodes are mapped to corresponding isolate embeddings (LRI, RLI, PDI). Direct input of the LRI/RLI/PDI control characters is not implemented. Given that there does not exists a dir node corresponding to FSI, FSI is not supported. This corrsponds to the conformance class "Non-isolate bidirectionality" and use of higher level protocol rule HL3
- Similarly to FSI, automatic detection of the paragraph direction is not done. LuaTeX's \pardir is used instead.  (Permitted by higher level protocol rule HL1)
- Unmatched PDI (aka dir nodes of subtype 1) are removed. This should not have any observable effect because LuaTeX always inserts another dir node after them. This is required to keep LuaTeX happy.
- For unmatched RLI/LRI (aka dir nodes of subtype 0) matching PDIs are appended at the end in front of any discardable elements. (Ensures proper end of paragraph behaviour)

**Comment by zauguin** [comment]
@u-fischer I created a new PR for a version without merge conflicts. I didn't want to push it here because I wanted to keep by bidi branch "pure".

**Comment by zauguin** [comment]
@khaledhosny You probably have significantly more experience with this, so are any of the above points serious problems? Especially are Unicode's directional isolates used a lot?

**Comment by u-fischer** [comment]
@zauguin  how does the code here relates to the bidi code in babel? Is there coordination needed?

**Comment by zauguin** [comment]
@u-fischer I wasn't aware that babel even had such a system and they shouldn't be used together. The most important differences seem to be that this implements paired brackets and most of the explicit formatting characters, while they are seem to be ignored by babel. This should make the babel code a bit faster, but I didn't do any benchmarks.
I implemented this only to make multiscript more useful, so if the babel version is sufficiently powerful we can probably drop this.

**Comment by khaledhosny** [comment]
> @khaledhosny You probably have significantly more experience with this, so are any of the above points serious problems? Especially are Unicode's directional isolates used a lot?

I prefer full compliance with the UBA, having suffered so many times from incompatible implementations. That being said, isolates area relatively new (but rather important) addition to the spec, and not as widely implemented (not even in web browser, where the need for them originated AFAIK).

**Comment by jbezos** [comment]
I can't try it out in a week or so, but I'll take a look at it and see if it can be integrated somehow with babel.

**Comment by jbezos** [comment]
I haven't managed to get it to work yet, but anyway some comments—

> I implemented this only to make multiscript more useful, so if the babel version is sufficiently powerful we can probably drop this.

I wouldn't impose the use of `babel` to get proper bidi writing. Both methods can co-exists, provided they can be turned on and off by the user. This is one of the reasons it must be requested explicitly in `babel` with the option `bidi`.

`babel` doesn't currently understand formatting characters because according to sec. 2.7, «Where available, markup should be used instead of the explicit formatting characters», and as to the paired brackets, I intended to add them shortly, but I had other priorities, including a recursive analysis of boxes (eg, a neutral or a hyphen inside an `\hbox`, for example).

**Comment by jbezos** [comment]
Please, could you help me with the following error? (`kpsewhich` finds the file luaotfload-bidi.lua`):

```
LaTeX2e <2018-12-01>
Lua module: luaotfload-main 2019-08-02 2.9905 luaotfload entry point
Lua module: luaotfload-init 2019-08-02 2.9905 luaotfload submodule / initializat
ion
Lua module: lualibs 2019-08-02 2.6703 ConTeXt Lua standard libraries.
Lua module: lualibs-extended 2019-08-02 2.6703 ConTeXt Lua libraries -- extended
 collection.
Lua module: luaotfload-log 2019-08-02 2.9905 luaotfload submodule / logging
Lua module: luaotfload-parsers 2019-08-02 2.9905 luaotfload submodule / filelist
Lua module: luaotfload-configuration 2019-08-02 2.9905 luaotfload submodule / co
nfig file reader
luaotfload | conf : Root cache directory is C:/Aplicaciones/TeXLive/texmf-var/lu
atex-cache/generic/names.
luaotfload | init : Loading fontloader “fontloader-2019-08-02.lua” from kpse
-resolved path “c:/TeX/luaotfbidi/tex/luatex/luaotfload/fontloader-2019-08-02.
lua”.
Lua-only attribute luaotfload@state = 2
Lua-only attribute luaotfload@noligature = 3
Lua-only attribute luaotfload@syllabe = 4
luaotfload | init : Context OpenType loader version “3.109”
Inserting `luaotfload.node_processor' at position 1 in `pre_linebreak_filter'.
Inserting `luaotfload.node_processor' at position 1 in `hpack_filter'.
Lua module: luaotfload-loaders 2019-08-02 2.9905 luaotfload submodule / callback
 handling
Inserting `luaotfload.define_font' at position 1 in `define_font'.
Lua module: luaotfload-database 2019-08-02 2.9905 luaotfload submodule / databas
e
Lua module: luaotfload-unicode 2019-08-02 2.9905 luaotfload submodule / Unicode 
helpers
Lua module: luaotfload-colors 2019-08-02 2.9905 luaotfload submodule / color
Lua-only attribute luaotfload_color_attribute = 5
Lua module: luaotfload-resolvers 2019-08-02 2.9905 luaotfload submodule / resolv
ers
luaotfload | conf : Root cache directory is C:/Aplicaciones/TeXLive/texmf-var/lu
atex-cache/generic/names.
Lua module: luaotfload-features 2019-08-02 2.9905 luaotfload submodule / feature
s
Lua module: luaotfload-letterspace 2019-08-02 2.9905 luaotfload submodule / colo
r
Lua module: luaotfload-embolden 2019-08-02 2.9905 luaotfload submodule / color
Lua module: luaotfload-notdef 2019-08-02 2.9905 luaotfload submodule / color
Lua module: luaotfload-auxiliary 2019-08-02 2.9905 luaotfload submodule / auxili
ary functions
Inserting `luaotfload.aux.set_sscale_dimens' at position 1 in `luaotfload.patch_
font'.
Inserting `luaotfload.aux.patch_cambria_domh' at position 2 in `luaotfload.patch
_font'.
Inserting `luaotfload.aux.fixup_fontdata' at position 1 in `luaotfload.patch_fon
t_unsafe'.
Inserting `luaotfload.aux.set_capheight' at position 3 in `luaotfload.patch_font
'.
Inserting `luaotfload.aux.set_xheight' at position 4 in `luaotfload.patch_font'.
Lua module: luaotfload-bidi 2019-08-02 2.9904 luaotfload submodule / bidi
luaotfload | load : FATAL ERROR
luaotfload | load :   × Failed to load module "luaotfload-bidi.lua".
luaotfload | load :   × Error message:
luaotfload | load :     × "[string \"-- luatex-core security and io overloads .
......\"]:45: bad argument #1 to 'io_open' (string expected, got nil)".
```

**Comment by zauguin** [comment]
@jbezos Probably your version of `unicode-data` ist outbif Data. luaotfload-bidi.lua doesn't find some data files provided by that package.

**Comment by u-fischer** [comment]
This has been merged through #83.

**Pull request closed without merging**
